services:
  inventory-database:
    image: inventory-database-postgres
    pull_policy: never
    container_name: inventory-database-postgres
    build:
      context: ./Inventory/Database/
      dockerfile: Dockerfile
    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data
    env_file:
      - ./Inventory/Database/database.env
    ports:
      - 5432:5432

volumes:
  inventory-postgres-data:
